grails-app/domain/com/invbox/bo/History.groovy
package com.invbox.bo;

class History {

	String itemcode
	String itemdescription
	Double listprice
	String marketplacecode
	Date searchdate
//	Userprofile userprofile
	Date dateCreated
	
	

	static belongsTo = [ userprofile : Userprofile ]

//	static mapping = {
//		id column: "historycode"
//		version false
//	}

	static constraints = {
		itemcode nullable: false
		itemdescription nullable: true
		listprice nullable: true
		marketplacecode nullable: true
		searchdate nullable: true
	}
}

grails-app/controllers/com/invbox/bo/HistoryController.groovy
package com.invbox.bo

import grails.converters.*;

class HistoryController {

	static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

	def index = {
		redirect(action: "list", params: params)
	}

	def list = {
		if(!params.max) params.max = 10
		def list = History.list(params)
		def count = History.count()
		if("xml".equals(params.requesttype)){
			render list as XML
		}else if("json".equals(params.requesttype)){
			render list as JSON
		}else{
			render list as JSON
		}
	}
	def create = {
		def historyInstance = new History()
		historyInstance.properties = params
		return [historyInstance: historyInstance]
	}

	def save = {
		def historyInstance = new History(params)
		log.warn "params:: ${params}"
		if (historyInstance.save(flush: true)) {
			flash.message = "${message(code: 'default.created.message', args: [message(code: 'history.label', default: 'History'), historyInstance.id])}"
			redirect(action: "show", id: historyInstance.id)
		}
		else {
			render(view: "create", model: [historyInstance: historyInstance])
		}
	}

	def show = {
		def historyInstance = History.get(params.id)
		if (!historyInstance) {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'history.label', default: 'History'), params.id])}"
			redirect(action: "list111")
		}
		else {
			[historyInstance: historyInstance]
		}
	}

	def edit = {
		def historyInstance = History.get(params.id)
		if (!historyInstance) {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'history.label', default: 'History'), params.id])}"
			redirect(action: "list111")
		}
		else {
			return [historyInstance: historyInstance]
		}
	}

	def update = {
		def historyInstance = History.get(params.id)
		if (historyInstance) {
			if (params.version) {
				def version = params.version.toLong()
				if (historyInstance.version > version) {

					historyInstance.errors.rejectValue("version", "default.optimistic.locking.failure", [
						message(code: 'history.label', default: 'History')]
					as Object[], "Another user has updated this History while you were editing")
					render(view: "edit", model: [historyInstance: historyInstance])
					return
				}
			}
			historyInstance.properties = params
			if (!historyInstance.hasErrors() && historyInstance.save(flush: true)) {
				flash.message = "${message(code: 'default.updated.message', args: [message(code: 'history.label', default: 'History'), historyInstance.id])}"
				redirect(action: "show", id: historyInstance.id)
			}
			else {
				render(view: "edit", model: [historyInstance: historyInstance])
			}
		}
		else {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'history.label', default: 'History'), params.id])}"
			redirect(action: "list111")
		}
	}

	def delete = {
		def historyInstance = History.get(params.id)
		if (historyInstance) {
			try {
				historyInstance.delete(flush: true)
				flash.message = "${message(code: 'default.deleted.message', args: [message(code: 'history.label', default: 'History'), params.id])}"
				redirect(action: "list111")
			}
			catch (org.springframework.dao.DataIntegrityViolationException e) {
				flash.message = "${message(code: 'default.not.deleted.message', args: [message(code: 'history.label', default: 'History'), params.id])}"
				redirect(action: "show", id: params.id)
			}
		}
		else {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'history.label', default: 'History'), params.id])}"
			redirect(action: "list111")
		}
	}
}

grails-app/views/history/create.gsp
<%@ page import="com.invbox.bo.History" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'history.label', default: 'History')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></span>
            <span class="menuButton"><g:link class="list" action="list111"><g:message code="default.list.label" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${historyInstance}">
            <div class="errors">
                <g:renderErrors bean="${historyInstance}" as="list" />
            </div>
            </g:hasErrors>
            <g:form action="save" >
                <div class="dialog">
                    <table>
                        <tbody>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="itemcode"><g:message code="history.itemcode.label" default="Itemcode" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: historyInstance, field: 'itemcode', 'errors')}">
                                    <g:textField name="itemcode" value="${historyInstance?.itemcode}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="listprice"><g:message code="history.listprice.label" default="Listprice" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: historyInstance, field: 'listprice', 'errors')}">
                                    <g:textField name="listprice" value="${fieldValue(bean: historyInstance, field: 'listprice')}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="marketplacecode"><g:message code="history.marketplacecode.label" default="Marketplacecode" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: historyInstance, field: 'marketplacecode', 'errors')}">
                                    <g:textField name="marketplacecode" value="${historyInstance?.marketplacecode}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="searchdate"><g:message code="history.searchdate.label" default="Searchdate" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: historyInstance, field: 'searchdate', 'errors')}">
                                    <g:datePicker name="searchdate" precision="day" value="${historyInstance?.searchdate}"  />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="userprofile"><g:message code="history.userprofile.label" default="Userprofile" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: historyInstance, field: 'userprofile', 'errors')}">
                                    <g:select name="userprofile.id" from="${com.invbox.bo.Userprofile.list()}" optionKey="id" value="${historyInstance?.userprofile?.id}"  />
                                </td>
                            </tr>
                        
                        </tbody>
                    </table>
                </div>
                <div class="buttons">
                    <span class="button"><g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" /></span>
                </div>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/history/edit.gsp
<%@ page import="com.invbox.bo.History" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'history.label', default: 'History')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></span>
            <span class="menuButton"><g:link class="list" action="list111"><g:message code="default.list.label" args="[entityName]" /></g:link></span>
            <span class="menuButton"><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${historyInstance}">
            <div class="errors">
                <g:renderErrors bean="${historyInstance}" as="list" />
            </div>
            </g:hasErrors>
            <g:form method="post" >
                <g:hiddenField name="id" value="${historyInstance?.id}" />
                <g:hiddenField name="version" value="${historyInstance?.version}" />
                <div class="dialog">
                    <table>
                        <tbody>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="itemcode"><g:message code="history.itemcode.label" default="Itemcode" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: historyInstance, field: 'itemcode', 'errors')}">
                                    <g:textField name="itemcode" value="${historyInstance?.itemcode}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="listprice"><g:message code="history.listprice.label" default="Listprice" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: historyInstance, field: 'listprice', 'errors')}">
                                    <g:textField name="listprice" value="${fieldValue(bean: historyInstance, field: 'listprice')}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="marketplacecode"><g:message code="history.marketplacecode.label" default="Marketplacecode" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: historyInstance, field: 'marketplacecode', 'errors')}">
                                    <g:textField name="marketplacecode" value="${historyInstance?.marketplacecode}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="searchdate"><g:message code="history.searchdate.label" default="Searchdate" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: historyInstance, field: 'searchdate', 'errors')}">
                                    <g:datePicker name="searchdate" precision="day" value="${historyInstance?.searchdate}"  />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                  <label for="userprofile"><g:message code="history.userprofile.label" default="Userprofile" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: historyInstance, field: 'userprofile', 'errors')}">
                                    <g:select name="userprofile.id" from="${com.invbox.bo.Userprofile.list()}" optionKey="id" value="${historyInstance?.userprofile?.id}"  />
                                </td>
                            </tr>
                        
                        </tbody>
                    </table>
                </div>
                <div class="buttons">
                    <span class="button"><g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" /></span>
                    <span class="button"><g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" /></span>
                </div>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/history/list111.gsp
<%@ page import="com.invbox.bo.History" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'history.label', default: 'History')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></span>
            <span class="menuButton"><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <div class="list">
                <table>
                    <thead>
                        <tr>
                        
                            <g:sortableColumn property="id" title="${message(code: 'history.id.label', default: 'Id')}" />
                        
                            <g:sortableColumn property="itemcode" title="${message(code: 'history.itemcode.label', default: 'Itemcode')}" />
                        
                            <g:sortableColumn property="listprice" title="${message(code: 'history.listprice.label', default: 'Listprice')}" />
                        
                            <g:sortableColumn property="marketplacecode" title="${message(code: 'history.marketplacecode.label', default: 'Marketplacecode')}" />
                        
                            <g:sortableColumn property="searchdate" title="${message(code: 'history.searchdate.label', default: 'Searchdate')}" />
                        
                            <g:sortableColumn property="dateCreated" title="${message(code: 'history.dateCreated.label', default: 'Date Created')}" />
                        
                        </tr>
                    </thead>
                    <tbody>
                    <g:each in="${historyInstanceList}" status="i" var="historyInstance">
                        <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
                        
                            <td><g:link action="show" id="${historyInstance.id}">${fieldValue(bean: historyInstance, field: "id")}</g:link></td>
                        
                            <td>${fieldValue(bean: historyInstance, field: "itemcode")}</td>
                        
                            <td>${fieldValue(bean: historyInstance, field: "listprice")}</td>
                        
                            <td>${fieldValue(bean: historyInstance, field: "marketplacecode")}</td>
                        
                            <td><g:formatDate date="${historyInstance.searchdate}" /></td>
                        
                            <td><g:formatDate date="${historyInstance.dateCreated}" /></td>
                        
                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </div>
            <div class="paginateButtons">
                <g:paginate total="${historyInstanceTotal}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/history/show.gsp
<%@ page import="com.invbox.bo.History" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'history.label', default: 'History')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></span>
            <span class="menuButton"><g:link class="list" action="list111"><g:message code="default.list.label" args="[entityName]" /></g:link></span>
            <span class="menuButton"><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <div class="dialog">
                <table>
                    <tbody>
                    
                        <tr class="prop">
                            <td valign="top" class="name"><g:message code="history.id.label" default="Id" /></td>
                            
                            <td valign="top" class="value">${fieldValue(bean: historyInstance, field: "id")}</td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name"><g:message code="history.itemcode.label" default="Itemcode" /></td>
                            
                            <td valign="top" class="value">${fieldValue(bean: historyInstance, field: "itemcode")}</td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name"><g:message code="history.listprice.label" default="Listprice" /></td>
                            
                            <td valign="top" class="value">${fieldValue(bean: historyInstance, field: "listprice")}</td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name"><g:message code="history.marketplacecode.label" default="Marketplacecode" /></td>
                            
                            <td valign="top" class="value">${fieldValue(bean: historyInstance, field: "marketplacecode")}</td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name"><g:message code="history.searchdate.label" default="Searchdate" /></td>
                            
                            <td valign="top" class="value"><g:formatDate date="${historyInstance?.searchdate}" /></td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name"><g:message code="history.dateCreated.label" default="Date Created" /></td>
                            
                            <td valign="top" class="value"><g:formatDate date="${historyInstance?.dateCreated}" /></td>
                            
                        </tr>
                    
                        <tr class="prop">
                            <td valign="top" class="name"><g:message code="history.userprofile.label" default="Userprofile" /></td>
                            
                            <td valign="top" class="value"><g:link controller="userprofile" action="show" id="${historyInstance?.userprofile?.id}">${historyInstance?.userprofile?.encodeAsHTML()}</g:link></td>
                            
                        </tr>
                    
                    </tbody>
                </table>
            </div>
            <div class="buttons">
                <g:form>
                    <g:hiddenField name="id" value="${historyInstance?.id}" />
                    <span class="button"><g:actionSubmit class="edit" action="edit" value="${message(code: 'default.button.edit.label', default: 'Edit')}" /></span>
                    <span class="button"><g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" /></span>
                </g:form>
            </div>
        </div>
    </body>
</html>