grails-app/domain/com/invbox/bo/Item.groovy
package com.invbox.bo

class Item {

	String itemcode
	String itemname
	String profilecode
	String itemdescription
	Double purchaseprice
	Date purchasedate
	String image
//	Integer categorycode
	String type
	String status
	String createdby
	Date creationdate
	String lastmodifiedby
	Date lastmodifieddate
	
	static mapping = {
		version false
	}
	
	static belongsTo = [category: Category]

	static constraints = {
		itemcode nullable: true
		itemname nullable: true, maxSize: 512
		itemdescription nullable: true, maxSize: 65535
		purchaseprice nullable: true
		purchasedate nullable: true
		image nullable: true
		type nullable: true
		status nullable: true
		createdby nullable: true
		creationdate nullable: true
		lastmodifiedby nullable: true
		lastmodifieddate nullable: true
		profilecode nullable: true
	}
}

grails-app/controllers/com/invbox/bo/FileResourceController.groovy
package com.invbox.bo

class FileResourceController {
    
    def index = { redirect(action:filelist,params:params) }
	static transactional = true
    
    def allowedMethods = []

    def filelist = {
		def fileResourceInstanceList = []
		def f = new File( grailsApplication.config.images.location.toString() )
		if( f.exists() ){
			f.eachFile(){ file->
			if( !file.isDirectory() )
				fileResourceInstanceList.add( file.name )
			}
		}
        [ fileResourceInstanceList: fileResourceInstanceList ]
    }

    def delete = {
		def filename = params.id.replace('###', '.')
		def file = new File( grailsApplication.config.images.location.toString() + File.separatorChar +   filename )
		file.delete()
		flash.message = "file ${filename} removed" 
		redirect( action:filelist )
    }

	def upload = {
		def f = request.getFile('fileUpload')
		println(request)
	    if(!f.empty) {
	      flash.message = 'Your file has been uploaded'
		  new File( grailsApplication.config.images.location.toString() ).mkdirs()
		  f.transferTo( new File( grailsApplication.config.images.location.toString() + File.separatorChar + f.getOriginalFilename() ) )								             			     	
		}    
	    else {
	       flash.message = 'file cannot be empty'
	    }
		redirect( action:filelist)
	}
}

grails-app/controllers/com/invbox/bo/ItemController.groovy
package com.invbox.bo

import grails.converters.*;
import org.springframework.web.multipart.support.DefaultMultipartHttpServletRequest;

class ItemController {

	/* Sample to control xml output for deep.
	 * class User {
	 String login
	 String name
	 String password
	 }
	 def converter = new XML(aUser)
	 converter.registerObjectMarshaller(User, {user, conv ->
	 conv.build {
	 login(user.login)
	 name(user.name)
	 }
	 })
	 or you could set the converter for the entire system by putting the same code in Bootstrap.groovy
	 grails.converters.XML.registerObjectMarshaller(User) { user, converter ->
	 // same implementation as above...
	 }
	 */

	static allowedMethods = [save: "POST", update: "POST", delete: "POST", getItemsForSellForItemId: "GET"]

	def index = {
		redirect(action: "list", params: params)
	}

	//	def index = { redirect(action:filelist,params:params) }

	def list = {
		grails.converters.XML.use('deep')
		params.max = Math.min(params.max ? params.int('max') : 10, 100)
		[itemInstanceList: Item.list(params), itemInstanceTotal: Item.count()]
	}

	def create = {
		def itemInstance = new Item()
		itemInstance.properties = params
		return [itemInstance: itemInstance]
	}

	def save = {
		def itemInstance = new Item(params)
		if (itemInstance.save(flush: true)) {
			//            flash.message = "${message(code: 'default.created.message', args: [message(code: 'item.label', default: 'Item'), itemInstance.id])}"
			//            redirect(action: "show", id: itemInstance.id)
			if("xml".equals(params.requesttype)){
				render itemInstance as XML
			}else if("json".equals(params.requesttype)){
				render itemInstance as JSON
			}else{
				render itemInstance as JSON
			}
		}
		else {
			//            render(view: "create", model: [itemInstance: itemInstance])
			if("xml".equals(params.requesttype)){
				render itemInstance.errors as XML
			}else if("json".equals(params.requesttype)){
				render itemInstance.errors as JSON
			}else{
				render itemInstance.errors as JSON
			}
		}
	}

	def show = {
		grails.converters.XML.use('deep')
		def itemInstance = Item.get(params.id)
		if (!itemInstance) {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'item.label', default: 'Item'), params.id])}"
			//			redirect(action: "list")
			render itemInstance.errors as XML
		}
		else {
			render itemInstance as XML
			//			render(view: "edit", model: [itemInstance: itemInstance])
		}
	}

	def edit = {
		grails.converters.XML.use('deep')
		def itemInstance = Item.get(params.id)
		if (!itemInstance) {
			//            flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'item.label', default: 'Item'), params.id])}"
			//            redirect(action: "list")
			render (itemInstance.errors) as XML
		}
		else {
			render (itemInstance) as XML
		}
	}

	def update = {
		def itemInstance = Item.get(params.id)
		if (itemInstance) {
			if (params.version) {
				def version = params.version.toLong()
				if (itemInstance.version > version) {

					itemInstance.errors.rejectValue("version", "default.optimistic.locking.failure", [
						message(code: 'item.label', default: 'Item')]
					as Object[], "Another user has updated this Item while you were editing")
					render (itemInstance.errors) as XML
					return
				}
			}
			itemInstance.properties = params
			if (!itemInstance.hasErrors() && itemInstance.save(flush: true)) {
				flash.message = "${message(code: 'default.updated.message', args: [message(code: 'item.label', default: 'Item'), itemInstance.id])}"
				render itemInstance as XML
			}
			else {
				render (itemInstance.errors) as XML
			}
		}
		else {
			//			if (!itemInstance.hasErrors() && itemInstance.save(flush: true)) {
			//				flash.message = "${message(code: 'default.updated.message', args: [message(code: 'item.label', default: 'Item'), itemInstance.id])}"
			//				render (itemInstance) as XML
			//			}
			//			else {
			render(view: "edit", model: [itemInstance: itemInstance])
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'item.label', default: 'Item'), params.id])}"
			redirect(action: "list")
			//				render (itemInstance.errors) as XML
			//			}
		}
	}

	def delete = {
		def itemInstance = Item.get(params.id)
		if (itemInstance) {
			try {
				itemInstance.delete(flush: true)
				flash.message = "${message(code: 'default.deleted.message', args: [message(code: 'item.label', default: 'Item'), params.id])}"
				redirect(action: "list")
			}
			catch (org.springframework.dao.DataIntegrityViolationException e) {
				flash.message = "${message(code: 'default.not.deleted.message', args: [message(code: 'item.label', default: 'Item'), params.id])}"
				redirect(action: "show", id: params.id)
			}
		}
		else {
			flash.message = "${message(code: 'default.not.found.message', args: [message(code: 'item.label', default: 'Item'), params.id])}"
			redirect(action: "list")
		}
	}

	def getItemsForSellForItemId = {

		grails.converters.XML.use('deep')
		if(!params.itemcode) return

			def c = Item.createCriteria()
		def results = c.list {
			and{
				eq("itemcode", params.itemcode)
				eq("status","market")
				eq("type","sell")
			}
		}

		if(!results) render results.errors as XML

		render results as XML
	}
	
	def getItemsForSale = {
		
				grails.converters.XML.use('deep')
				if(!params.itemcode) return
		
					def c = Item.createCriteria()
				def results = c.list {
					and{
						or{
							eq("itemcode", params.itemcode)
							like("itemname","%"+params.itemcode+"%")
							like("itemdescription","%"+params.itemcode+"%")
						}
						
						eq("status","market")
						eq("type","sell")
					}
				}
		
				if(!results) render results.errors as XML
		
				render results as XML
			}


	def getItemsCountForItemCode = {

		grails.converters.XML.use('deep')
		if(!params.itemcode) return

			def c = Item.createCriteria()
		def results = c.get {
			projections{ count('itemcode') }
			and{
				//				try{
				//					eq("itemcode", Long.parseLong(params.itemcode))
				//				}
				//				catch(Exception e){
				eq("itemcode", params.itemcode)
				//				}
				eq("status","market")
				eq("type",params.type)
				ne("profilecode",params.userid)
			}
		}
		render results
	}

	static transactional = true


	def filelist = {
		def fileResourceInstanceList = []
		def f = new File( grailsApplication.config.images.location.toString() )
		if( f.exists() ){
			f.eachFile(){ file->
				if( !file.isDirectory() )
					fileResourceInstanceList.add( file.name )
			}
		}
		[ fileResourceInstanceList: fileResourceInstanceList ]
	}

	def deletefile = {
		def filename = params.id.replace('###', '.')
		def file = new File( grailsApplication.config.images.location.toString() + File.separatorChar +   filename )
		file.delete()
		flash.message = "file ${filename} removed"
		redirect( action:upload )
	}

	def upload = {
		def f = request.getFile('fileUpload')
		println  grailsApplication.config.images.location.toString() + File.separatorChar + f.getOriginalFilename()
		if(!f.empty) {
			flash.message = 'Your file has been uploaded'
			new File( grailsApplication.config.images.location.toString() ).mkdirs()
			f.transferTo( new File( grailsApplication.config.images.location.toString() + File.separatorChar + f.getOriginalFilename() ) )
		}
		else {
			flash.message = 'file cannot be empty'
		}
		redirect( action:filelist)
	}
}

grails-app/views/item/create.gsp
<%@ page import="com.invbox.bo.Item" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'item.label', default: 'Item')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></span>
            <span class="menuButton"><g:link class="list" action="list"><g:message code="default.list.label" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${itemInstance}">
            <div class="errors">
                <g:renderErrors bean="${itemInstance}" as="list" />
            </div>
            </g:hasErrors>
            <g:form action="save" >
                <div class="dialog">
                    <table>
                        <tbody>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="itemcode"><g:message code="item.itemcode.label" default="Itemcode" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'itemcode', 'errors')}">
                                    <g:textField name="itemcode" value="${fieldValue(bean: itemInstance, field: 'itemcode')}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="itemname"><g:message code="item.itemname.label" default="Itemname" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'itemname', 'errors')}">
                                    <g:textArea name="itemname" cols="40" rows="5" value="${itemInstance?.itemname}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="itemdescription"><g:message code="item.itemdescription.label" default="Itemdescription" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'itemdescription', 'errors')}">
                                    <g:textArea name="itemdescription" cols="40" rows="5" value="${itemInstance?.itemdescription}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="purchaseprice"><g:message code="item.purchaseprice.label" default="Purchaseprice" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'purchaseprice', 'errors')}">
                                    <g:textField name="purchaseprice" value="${fieldValue(bean: itemInstance, field: 'purchaseprice')}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="purchasedate"><g:message code="item.purchasedate.label" default="Purchasedate" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'purchasedate', 'errors')}">
                                    <g:datePicker name="purchasedate" precision="day" value="${itemInstance?.purchasedate}" default="none" noSelection="['': '']" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="image"><g:message code="item.image.label" default="Image" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'image', 'errors')}">
                                    <g:textField name="image" value="${itemInstance?.image}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="type"><g:message code="item.type.label" default="Type" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'type', 'errors')}">
                                    <g:textField name="type" value="${itemInstance?.type}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="status"><g:message code="item.status.label" default="Status" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'status', 'errors')}">
                                    <g:textField name="status" value="${itemInstance?.status}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="createdby"><g:message code="item.createdby.label" default="Createdby" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'createdby', 'errors')}">
                                    <g:textField name="createdby" value="${itemInstance?.createdby}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="creationdate"><g:message code="item.creationdate.label" default="Creationdate" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'creationdate', 'errors')}">
                                    <g:datePicker name="creationdate" precision="day" value="${itemInstance?.creationdate}" default="none" noSelection="['': '']" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="lastmodifiedby"><g:message code="item.lastmodifiedby.label" default="Lastmodifiedby" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'lastmodifiedby', 'errors')}">
                                    <g:textField name="lastmodifiedby" value="${itemInstance?.lastmodifiedby}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="lastmodifieddate"><g:message code="item.lastmodifieddate.label" default="Lastmodifieddate" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'lastmodifieddate', 'errors')}">
                                    <g:datePicker name="lastmodifieddate" precision="day" value="${itemInstance?.lastmodifieddate}" default="none" noSelection="['': '']" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="profilecode"><g:message code="item.profilecode.label" default="Profilecode" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'profilecode', 'errors')}">
                                    <g:textField name="profilecode" value="${itemInstance?.profilecode}" />
                                </td>
                            </tr>
                        
                            <tr class="prop">
                                <td valign="top" class="name">
                                    <label for="category"><g:message code="item.category.label" default="Category" /></label>
                                </td>
                                <td valign="top" class="value ${hasErrors(bean: itemInstance, field: 'category', 'errors')}">
                                    <g:select name="category.id" from="${com.invbox.bo.Category.list()}" optionKey="id" value="${itemInstance?.category?.id}"  />
                                </td>
                            </tr>
                        
                        </tbody>
                    </table>
                </div>
                <div class="buttons">
                    <span class="button"><g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" /></span>
                </div>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/item/filelist.gsp
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <meta name="layout" content="main" />
        <title>FileResource List</title>
    </head>
    <body>
        <div class="nav">
   			  <span class="menuButton"><a class="home" href="/">Home</a></span>
     </div>
        <div class="body">

			<h1>File Upload:</h1><br>

			 <g:form method="post"  enctype="multipart/form-data">
	                <div class="dialog">
	                    <table>
	                        <tbody>
	                            <tr class="prop">
	                                <td valign="top" class="name">
	                                    <label for="fileUpload">Upload:</label>
	                                </td>
	                                <td valign="top" class="value ${hasErrors(bean:fileResourceInstance,field:'upload','errors')}">
	                                    <input type="file" id="fileUpload" name="fileUpload" />
	                                </td>
	                            </tr> 
	                        </tbody>
	                    </table>
	                </div>
	                <div class="buttons">
	                    <span class="button"><g:actionSubmit class="upload" value="Upload" action="upload" /></span>
	                </div>
	            </g:form>

            
        </div>
    </body>
</html>

grails-app/views/item/list.gsp
<%@ page import="com.invbox.bo.Item" %>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'item.label', default: 'Item')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav">
            <span class="menuButton"><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></span>
            <span class="menuButton"><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></span>
        </div>
        <div class="body">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message">${flash.message}</div>
            </g:if>
            <div class="list">
                <table>
                    <thead>
                        <tr>
                        
                            <g:sortableColumn property="id" title="${message(code: 'item.id.label', default: 'Id')}" />
                        
                            <g:sortableColumn property="itemcode" title="${message(code: 'item.itemcode.label', default: 'Itemcode')}" />
                        
                            <g:sortableColumn property="itemname" title="${message(code: 'item.itemname.label', default: 'Itemname')}" />
                        
                            <g:sortableColumn property="itemdescription" title="${message(code: 'item.itemdescription.label', default: 'Itemdescription')}" />
                        
                            <g:sortableColumn property="purchaseprice" title="${message(code: 'item.purchaseprice.label', default: 'Purchaseprice')}" />
                        
                            <g:sortableColumn property="purchasedate" title="${message(code: 'item.purchasedate.label', default: 'Purchasedate')}" />
                        
                        </tr>
                    </thead>
                    <tbody>
                    <g:each in="${itemInstanceList}" status="i" var="itemInstance">
                        <tr class="${(i % 2) == 0 ? 'odd' : 'even'}">
                        
                            <td><g:link action="show" id="${itemInstance.id}">${fieldValue(bean: itemInstance, field: "id")}</g:link></td>
                        
                            <td>${fieldValue(bean: itemInstance, field: "itemcode")}</td>
                        
                            <td>${fieldValue(bean: itemInstance, field: "itemname")}</td>
                        
                            <td>${fieldValue(bean: itemInstance, field: "itemdescription")}</td>
                        
                            <td>${fieldValue(bean: itemInstance, field: "purchaseprice")}</td>
                        
                            <td><g:formatDate date="${itemInstance.purchasedate}" /></td>
                        
                        </tr>
                    </g:each>
                    </tbody>
                </table>
            </div>
            <div class="paginateButtons">
                <g:paginate total="${itemInstanceTotal}" />
            </div>
        </div>
    </body>
</html>